% rd_spmROIDataFromImg.m

filebase = '../../rois/any_vs_blank_posx_roi';

roi_file = sprintf('%s.mat', filebase);
beta_imgs = strvcat('beta_0001.img', 'beta_0002.img', ...
    'beta_0003.img', 'beta_0004.img', 'beta_0005.img', ...
    'beta_0006.img');

% f_imgs = 'spmF_0002.img';

imFiles = beta_imgs;

roi_obj = maroi(roi_file);
[Y multv vXYZ mat] = getdata(roi_obj, imFiles, 'l');
n_voxels = size(Y, 2);


% since beta imgs are somehow masked additionally compared to mask.img
% generated by spm, redo the beta value extraction outside of marsbar
clear vals
for iIm = 1:size(imFiles,1)
    imFile = imFiles(iIm,:)
    vals(iIm,:) = rd_spmGetValsFromImgAtCoords(imFile, vXYZ);
end

% plot some figs
figure
imagesc(vals(1:5,:)')

figure
scatter(mean(vals(1:4,:)), vals(5,:))
hold on
plot(-3:.5:3, -3:.5:3)

% save file
save(sprintf('%s_betas.mat', filebase), 'imFiles', 'roi_obj', ...
    'Y', 'multv', 'vXYZ', 'mat', 'vals')



